### ISSUE TITLE
nodetool status not showing dynamic pods joining

### ISSUE THREAD

**Issue by screeley44** [vyshane/cassandra-kubernetes#2]
@vyshane - hello, I'm experimenting with your examples, everything seems to run fine, I have an openshift 3.1 cluster running master + 1 node and gluster cluster on the backend for Persistent Volume support.

I created peer-service, service and rc and my pods run, and I'm using a glusterfs volume for data persistence, the data is persisted on multiple restarts of the pods/rc but when I scale I'm not seeing the pods join the C\* ring - and not sure what I'm missing.  I don't have a ton of experience with k8 or cassandra but from each container I can ping cassandra-peer (peer service)- so I know they are able to connect.

Unclear to me right now if I need to change my PEER_DISCOVERY_DOMAIN or something else?

```
      env:
        # Feel free to change the following:
        - name: CASSANDRA_CLUSTER_NAME
          value: Test Cluster
        - name: CASSANDRA_DC
          value: datacenter1
        - name: CASSANDRA_RACK
          value: rack1
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: GossipingPropertyFileSnitch

        # The peer discovery domain needs to point to the Cassandra peer service
        - name: PEER_DISCOVERY_DOMAIN
          value: cassandra-peers.default.cluster.local.
```

some output from oc (kubectl for openshift):
[root@ose1 cassandra-custom]# oc get pods
NAME              READY     STATUS    RESTARTS   AGE
cassandra-vfujv   1/1       Running   0          59s
cassandra-x36ay   1/1       Running   0          1m
[root@ose1 cassandra-custom]# oc exec -it cassandra-x36ay -- nodetool status testspace
# Datacenter: datacenter1

Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.1.0.32  176.43 KB  256          100.0%            03b19bd1-ce65-4525-89e7-b23c9b3f0a92  rack1
